# Generated by Django 4.1 on 2022-09-20 05:32

from django.db import migrations, models
import events.models
import uuid

class Migration(migrations.Migration):
    def generate_filename(instance, filename):
        extension = filename.split('.')[-1]
        new_filename = "foringLocation_%s.%s" % (uuid.uuid4(), extension)
        return new_filename

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to=events.models.generate_filename),
        ),
    ]
