# Generated by Django 4.1.1 on 2022-09-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location'),
        ('events', '0002_event_event_image'),
    ]

    operations = [
    ]
