# Generated by Django 4.1.1 on 2022-09-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_location_image'),
        ('events', '0003_merge_20220920_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locations.location'),
        ),
    ]
