# Generated by Django 4.1.1 on 2022-09-25 08:37

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_image_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to=events.models.generate_filename),
        ),
    ]
