# Generated by Django 4.1.1 on 2022-09-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=1500)),
                ('slug', models.SlugField(max_length=255)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
            ],
        ),
    ]
