# Generated by Django 4.1 on 2022-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
