# Generated by Django 4.1.1 on 2022-09-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_location_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=1500)),
                ('no_of_days', models.IntegerField()),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
            ],
        ),
    ]
