# Generated by Django 4.1 on 2022-09-20 05:32

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(null=True, upload_to=tours.models.generate_filename),
        ),
    ]
