# Generated by Django 4.1 on 2022-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
