# Generated by Django 4.1 on 2023-01-15 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_location_banner_image'),
        ('events', '0009_event_nod_event_price_alter_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('num_person_Adult', models.IntegerField(default=0, null=True)),
                ('num_person_Child', models.IntegerField(default=0, null=True)),
                ('journey_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('payment_status', models.BooleanField(default=False)),
                ('events', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='events.event')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='locations.location')),
            ],
        ),
    ]
