# Generated by Django 4.1.1 on 2022-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
