# Generated by Django 4.1.1 on 2022-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=1500)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
