# Generated by Django 4.1 on 2022-09-19 15:19

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_image',
            field=models.ImageField(null=True, upload_to=locations.models.generate_filename),
        ),
    ]
