# Generated by Django 4.1 on 2022-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
