# Generated by Django 4.1 on 2022-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
